@startuml Reconnect to last conected workspace
:User.WorkspaceId = config.json/WorkspaceId}
if (User.WorkspaceId != null) then (yes)
    :User.WorkspaceId
else (no)
    : config.json/WorkspaceId = User.WorkspaceId}
endif
@enduml